printl("Initiating TUMTaRA_Items.nut")
printl("-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=")
printl(" ")
printl("ITEM SPINNER CONTROLS.")
printl("Copy the string below into the console, then change Maxspeed 30 to whatever number you want.")
printl("You MUST add quotation marks around Maxspeed X. I can't write it out here. Printl commands (to write these messages) won't allow it.")
printl(" ")
printl("ent_fire turntable* addoutput maxspeed 30;ent_fire turntable* setspeed 1")
printl(" ")
printl("Reverse spinner direction.")
printl("ent_fire turntable* reverse")
printl(" ")
printl("Start/Stop rotation")
printl("ent_fire turntable_* toggle")
printl(" ")
printl("Change angle - Requires quotationmarks around ''angles x y z''. only change middle number.")
printl("ent_fire turntable_* addoutput angles 0 180 0")
printl(" ")
printl("-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=")
printl(" ")