printl("Initiating TUMTaRA_Infotext.nut")
printl("-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=")
printl(" ")
printl("Here's some useful console commands:")
printl(" ")
printl("enable_skeleton_draw 1		- Shows all bones, including viewmodel")
printl("bindtoggle KEY nb_stop		- Stops bot movement")
printl("cl_glow_blur_scale 0		- Disables outline glow")
printl("bind KEY sb_takecontrol 	- Take control of bot you're aiming at")
printl("bindtoggle KEY r_drawvgui 	- Toggles hud")
printl(" ")
printl("cl_jiggle_bone_debug                     0	, Display physics-based 'jiggle bone' debugging information")
printl("cl_jiggle_bone_debug_pitch_constraints   0	, Display physics-based 'jiggle bone' debugging information")
printl("cl_jiggle_bone_debug_yaw_constraints     0	, Display physics-based 'jiggle bone' debugging information")
printl(" ")
printl("bind KEY z_increment_head;z_increment_skin;z_increment_lower;z_increment_upper : Change look of CI you are aiming at")
printl(" ")
printl("Incap yourself using 'hurtme 100. Switch to another character using 'sb_takecontrol'.")
printl("Enable god mode (Console command 'god') to prevent death when incapped.")
printl(" ")
printl("-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=")
printl(" ")
